[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "parol-web-commander"
version = "1.0.0"
description = "Web interface for PAROL robot control"
requires-python = ">=3.11"
dependencies = [
  "nicegui>=2.0.0",
  "python-dotenv>=1.0.0",
  "urchin>=0.0.27",
  "numpy>=1.24",
  "scipy>=1.10",
]

[project.optional-dependencies]
dev = ["ruff", "mypy", "pytest", "pytest-asyncio", "pre-commit"]

[tool.ruff]
extend-exclude = [
  "external/",
  "PAROL*/"
]

[tool.mypy]
exclude = '(?x)(^external/|PAROL.*/)$'

[[tool.mypy.overrides]]
module = ["parol6", "parol6.*", "roboticstoolbox", "roboticstoolbox.*", "spatialmath", "spatialmath.*"]
ignore_missing_imports = true

# ---- Pytest configuration ----
[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
asyncio_mode = "auto"
addopts = [
    "--strict-markers",
    "--strict-config",
    "-ra",  # show short test summary for all but passes
]
markers = [
    "unit: Unit tests",
    "integration: Integration tests",
]
