[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "parol-web-commander"
version = "1.0.0"
description = "NiceGUI-based web interface for PAROL6 robot control"
requires-python = ">=3.11"
dependencies = [
    "nicegui>=2.0.0",
    "python-dotenv>=1.0.0",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.1.0",
    "mypy>=1.5.0",
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "pre-commit>=3.0.0",
]

# ---- Ruff configuration ----
[tool.ruff]
target-version = "py311"
line-length = 100
fix = true

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # Pyflakes
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "I",   # isort
    "C4",  # flake8-comprehensions
    "TCH", # flake8-type-checking
]
ignore = [
    "E501",   # line too long (handled by formatter)
    "B008",   # function calls in argument defaults (common in FastAPI/NiceGUI)
    "UP007",  # use X | Y union syntax (prefer typing.Union for py3.9+ compat if needed)
]

[tool.ruff.lint.isort]
known-first-party = ["app", "services", "pages"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

# ---- MyPy configuration ----
[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false  # relaxed for UI code with many callbacks
disallow_incomplete_defs = false
check_untyped_defs = true
disallow_untyped_decorators = false  # NiceGUI decorators often untyped
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
no_implicit_reexport = true

[[tool.mypy.overrides]]
module = [
    "nicegui.*",
    "PAROL6_ROBOT",
    "customtkinter.*",
]
ignore_missing_imports = true

# ---- Pytest configuration ----
[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
asyncio_mode = "auto"
addopts = [
    "--strict-markers",
    "--strict-config",
    "-ra",  # show short test summary for all but passes
]
markers = [
    "unit: Unit tests",
    "integration: Integration tests",
]
